In [24]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset


In [25]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

print(X.shape, y.shape)

(50, 4) (50,)


# Encoding the Independent Variable (State)

In [26]:
# Encoding the Independent variable (dummy encoding)
from sklearn.preprocessing import OneHotEncoder

onehotencoder_X1 = OneHotEncoder()
X1 = X[:, 3].reshape(-1, 1)#make sure x1 is 2 dimension, row = -1 means don't care. choose the row3 (state col) 
onehotX1_result = onehotencoder_X1.fit_transform(X1).toarray()
#onehotencoder_X1.categories_
# print(onehotX1_result)

X = np.c_[X[:, 0:3],onehotX1_result] # c_ means combine., we throw the first column
print(X) # now X state is change to the one hot encoder data. 


[[165349.2 136897.8 471784.1 0.0 0.0 1.0]
 [162597.7 151377.59 443898.53 1.0 0.0 0.0]
 [153441.51 101145.55 407934.54 0.0 1.0 0.0]
 [144372.41 118671.85 383199.62 0.0 0.0 1.0]
 [142107.34 91391.77 366168.42 0.0 1.0 0.0]
 [131876.9 99814.71 362861.36 0.0 0.0 1.0]
 [134615.46 147198.87 127716.82 1.0 0.0 0.0]
 [130298.13 145530.06 323876.68 0.0 1.0 0.0]
 [120542.52 148718.95 311613.29 0.0 0.0 1.0]
 [123334.88 108679.17 304981.62 1.0 0.0 0.0]
 [101913.08 110594.11 229160.95 0.0 1.0 0.0]
 [100671.96 91790.61 249744.55 1.0 0.0 0.0]
 [93863.75 127320.38 249839.44 0.0 1.0 0.0]
 [91992.39 135495.07 252664.93 1.0 0.0 0.0]
 [119943.24 156547.42 256512.92 0.0 1.0 0.0]
 [114523.61 122616.84 261776.23 0.0 0.0 1.0]
 [78013.11 121597.55 264346.06 1.0 0.0 0.0]
 [94657.16 145077.58 282574.31 0.0 0.0 1.0]
 [91749.16 114175.79 294919.57 0.0 1.0 0.0]
 [86419.7 153514.11 0.0 0.0 0.0 1.0]
 [76253.86 113867.3 298664.47 1.0 0.0 0.0]
 [78389.47 153773.43 299737.29 0.0 0.0 1.0]
 [73994.56 122782.75 303319.26 0.0

# Avoiding the Dummy Variable Trap


In [27]:
X = X[:, :-1] #去掉最後一個data，因為前兩者皆為0時，代表最後一個必為1
print(X[0:5,:])

[[165349.2 136897.8 471784.1 0.0 0.0]
 [162597.7 151377.59 443898.53 1.0 0.0]
 [153441.51 101145.55 407934.54 0.0 1.0]
 [144372.41 118671.85 383199.62 0.0 0.0]
 [142107.34 91391.77 366168.42 0.0 1.0]]



# Splitting the dataset into the Training set and Test set


In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)#40筆資料拿去做訓練，10筆資料拿來做測試
print(X_train[0:5,:])

(40, 5) (10, 5) (40,) (10,)
[[55493.95 103057.49 214634.81 0.0 1.0]
 [46014.02 85047.44 205517.64 0.0 0.0]
 [75328.87 144135.98 134050.07 0.0 1.0]
 [46426.07 157693.92 210797.67 1.0 0.0]
 [91749.16 114175.79 294919.57 0.0 1.0]]


# Fitting Multiple Linear Regression to the Training set


In [30]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

# Predicting the Test set results


In [33]:
y_pred = regressor.predict(X_test)
print('coef= ', regressor.coef_)
print('intercept= ', regressor.intercept_)
print('score= ', regressor.score(X, y))

coef=  [ 7.73467193e-01  3.28845975e-02  3.66100259e-02 -6.99369053e+02
 -1.65865321e+03]
intercept=  43253.53667068362
score=  0.9485223547173579


# Building the optimal model using Backward Elimination






In [41]:
import statsmodels.api as sm
# X_train = np.append(arr = np.ones((40, 1)), values = X_train, axis = 1)
X_train = sm.add_constant(X_train) # must have this line.
X_opt = X_train[:, [0, 1, 2, 3, 4,5]] # why need to write 0~5 (put all data into X_opt)
X_opt = np.array(X_opt, dtype='float') # change X_opt to np.array.


regressor_OLS = sm.OLS(y_train, X_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.943
Method:                 Least Squares   F-statistic:                     129.7
Date:                Tue, 08 Mar 2022   Prob (F-statistic):           3.91e-21
Time:                        06:48:13   Log-Likelihood:                -421.10
No. Observations:                  40   AIC:                             854.2
Df Residuals:                      34   BIC:                             864.3
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.325e+04   8315.816      5.201      0.0

In [42]:
X_opt = X_train[:, [0, 1, 3, 4, 5]] # 因為上面的x2的P VALUE > 0.05，所以我們就把2丟掉
X_opt = np.array(X_opt, dtype='float')
regressor_OLS = sm.OLS(endog = y_train, exog = X_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     165.6
Date:                Tue, 08 Mar 2022   Prob (F-statistic):           3.19e-22
Time:                        06:49:10   Log-Likelihood:                -421.24
No. Observations:                  40   AIC:                             852.5
Df Residuals:                      35   BIC:                             860.9
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.688e+04   3870.795     12.112      0.0

In [46]:
X_opt = X_train[:, [0, 1, 3,  5]] # 因為上面的4的P VALUE > 0.05，所以我們就把4丟掉
X_opt = np.array(X_opt, dtype='float')
regressor_OLS = sm.OLS(endog = y_train, exog = X_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     227.0
Date:                Tue, 08 Mar 2022   Prob (F-statistic):           1.96e-23
Time:                        06:51:04   Log-Likelihood:                -421.25
No. Observations:                  40   AIC:                             850.5
Df Residuals:                      36   BIC:                             857.3
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.653e+04   3069.509     15.159      0.0

In [47]:
X_opt = X_train[:, [0, 1, 3]] # 因為上面的5的P VALUE > 0.05，所以我們就把5丟掉
X_opt = np.array(X_opt, dtype='float')
regressor_OLS = sm.OLS(endog = y_train, exog = X_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.947
Method:                 Least Squares   F-statistic:                     349.0
Date:                Tue, 08 Mar 2022   Prob (F-statistic):           9.65e-25
Time:                        06:51:26   Log-Likelihood:                -421.30
No. Observations:                  40   AIC:                             848.6
Df Residuals:                      37   BIC:                             853.7
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.635e+04   2971.236     15.598      0.0

In [48]:
X_opt = X_train[:, [0, 1]] # 因為上面的3的P VALUE > 0.05，所以我們就把3丟掉
X_opt = np.array(X_opt, dtype='float')
regressor_OLS = sm.OLS(endog = y_train, exog = X_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.945
Model:                            OLS   Adj. R-squared:                  0.944
Method:                 Least Squares   F-statistic:                     652.4
Date:                Tue, 08 Mar 2022   Prob (F-statistic):           1.56e-25
Time:                        06:51:42   Log-Likelihood:                -423.09
No. Observations:                  40   AIC:                             850.2
Df Residuals:                      38   BIC:                             853.6
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.842e+04   2842.717     17.032      0.0