In [11]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
dataset = pd.read_csv('sample_data/Data.csv')
X = dataset.iloc[:,0:-1].values
y = dataset.iloc[:,3].values # 逗號前是取哪幾個row，後面是取哪幾個column
print(dataset)
print(X)
print(y)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [13]:
# Taking care of missing data.
from sklearn.impute import SimpleImputer
imputer = SimpleImputer()
imputer = imputer.fit(X[:,1:3])# 把有缺失的資料包進去
X[:,1:3] = imputer.transform(X[:,1:3])# 把填好的資料補回去
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [14]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder
# 幫label去做encoding的動作
labelencoder_y = LabelEncoder() 
y = labelencoder_y.fit_transform(y) # label yes or no.

print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]


In [15]:
# Encoding the Independent variable (dummy encoding)
from sklearn.preprocessing import OneHotEncoder
# onehotencoder = OneHotEncoder()
# X = onehotencoder.fit_transform(X).toarray()
# onehotencoder.categories_

X1 = X[:, 0].reshape(-1, 1)#make sure x1 is 2 dimension, row = -1 means don't care. 

onehotencoder_X1 = OneHotEncoder()
X1 = onehotencoder_X1.fit_transform(X1).toarray()
# onehotencoder_X1.categories_

print(X1)

X = np.c_[X1, X[:, 1:]] # c_ means combine., we throw the first column
print(X)


[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print('X_train:',X_train)
print('y_train:',y_train)
print('X_test:',X_test)
print('y_test:',y_test)

X_train: [[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
y_train: [1 1 1 0 1 0 0 1]
X_test: [[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 50.0 83000.0]]
y_test: [0 0]


In [7]:
# Feature Scaling # 年紀跟薪資大小差太多，所以要去做scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
# x = sc_x.fit_transform(x)
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
print('After scaling X_train:', X_train)
print('After scaling X_test:', X_test)


After scaling X_train: [[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]
After scaling X_test: [[-1.          2.64575131 -0.77459667 -1.45882927 -0.90166297]
 [-1.          2.64575131 -0.77459667  1.98496442  2.13981082]]
